kind: pipeline
type: docker
name: valentine-pipeline

steps:
  - name: install
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm install

  - name: test
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile
      - pnpm test
    depends_on:
      - install

  - name: build
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm build
    environment:
      VITE_BASE_URL: /valentine/
    depends_on:
      - test # build depends on test

  - name: deploy
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      pages_directory: dist
    when:
      branch:
        - main
    depends_on:
      - build # deploy depends on build
trigger:
  branch:
    - main
