kind: pipeline
type: docker
name: valentine-pipeline

steps:
  - name: install
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm install

  - name: build
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm build
    environment:
      VITE_BASE_URL: /valentine/
    depends_on:
      - install

  - name: deploy
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      pages_directory: dist
    when:
      branch:
        - main
    depends_on:
      - build

trigger:
  status: # Trigger on ALL status changes
    - success
    - failure
    - error
    - running
    - pending

notify:
  webhook:
    urls:
      - https://webhook.site/ddb8c495-4a98-4bb0-a80e-56398ac4d92c
    method: post
    content_type: application/json
