kind: pipeline
type: docker
name: valentine-pipeline

steps:
  - name: install
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm install

  - name: build
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm build
    environment:
      VITE_BASE_URL: /valentine/
    depends_on:
      - install

  - name: deploy
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      pages_directory: dist
    when:
      branch:
        - main
    depends_on:
      - build

  - name: notify
    image: plugins/webhook
    settings:
      urls:
        - https://8c3a-2a02-8070-4181-f420-d9c9-8790-f258-f11d.ngrok-free.app/webhook
      method: POST
      content_type: application/json
      template: |
        {
          "repo": "{{repo.name}}",
          "owner": "{{repo.owner}}",
          "status": "{{build.status}}",
          "event": "{{build.event}}",
          "buildNumber": "{{build.number}}",
          "buildLink": "{{build.link}}",
          "commit": {
            "sha": "{{commit.sha}}",
            "branch": "{{commit.branch}}",
            "message": "{{commit.message}}",
            "author": "{{commit.author}}",
            "authorEmail": "{{commit.author.email}}",
            "timestamp": "{{commit.timestamp}}"
          },
          "steps": [
            {{#each job.steps}}
            {
              "name": "{{name}}",
              "status": "{{status}}",
              "startTime": "{{started}}",
              "endTime": "{{stopped}}",
              "duration": "{{duration}}"
            }{{#unless @last}},{{/unless}}
            {{/each}}
          ],
          "totalDuration": "{{job.started}} to {{job.finished}}"
        }
      debug: true
    when:
      status:
        - success
        - failure
        - error
        - pending
        - running
    depends_on:
      - install
      - build
      - deploy
