kind: pipeline
type: docker
name: valentine-pipeline

steps:
  - name: install
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm install

  - name: build
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm build
    environment:
      VITE_BASE_URL: /valentine/
    depends_on:
      - install

  - name: deploy
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      pages_directory: dist
    when:
      branch:
        - main
    depends_on:
      - build

  - name: notify
    image: plugins/webhook
    settings:
      urls:
        - https://8c3a-2a02-8070-4181-f420-d9c9-8790-f258-f11d.ngrok-free.app/webhook
      method: POST
      content_type: application/json
      template: |
        {
          "repo": {
            "slug": "{{repo.slug}}"
          },
          "build": {
            "number": {{build.number}},
            "status": "{{build.status}}",
            "stages": [
              {{#each build.stages}}
              {
                "steps": [
                  {{#each steps}}
                  {
                    "name": "{{name}}",
                    "status": "{{status}}",
                    "started": {{started}},
                    "finished": {{finished}}
                  }
                  {{#unless @last}},{{/unless}}
                  {{/each}}
                ]
              }
              {{#unless @last}},{{/unless}}
              {{/each}}
            ]
          }
        }
    when:
      status:
        - success
        - failure
        - error
