kind: pipeline
type: docker
name: valentine-pipeline

steps:
  - name: install
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm install

  - name: build
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm build
    environment:
      VITE_BASE_URL: /valentine/
    depends_on:
      - install

  - name: deploy
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      pages_directory: dist
    when:
      branch:
        - main
    depends_on:
      - build

  - name: notify
    image: plugins/webhook
    settings:
      urls:
        - https://8c3a-2a02-8070-4181-f420-d9c9-8790-f258-f11d.ngrok-free.app/webhook
      method: POST
      content_type: application/json
      template: |
        {
          "repo": {
            "slug": "{{repo.slug}}",
            "name": "{{repo.name}}",
            "owner": "{{repo.owner}}",
            "link": "{{repo.link}}"
          },
          "build": {
            "number": {{build.number}},
            "status": "{{build.status}}",
            "event": "{{build.event}}",
            "link": "{{build.link}}",
            "started": {{build.started}},
            "finished": {{build.finished}},
            "deployTarget": "{{build.deployTo}}"
          },
          "commit": {
            "sha": "{{commit.sha}}",
            "ref": "{{commit.ref}}",
            "branch": "{{commit.branch}}",
            "message": "{{commit.message}}",
            "author": "{{commit.author.login}}",
            "authorEmail": "{{commit.author.email}}",
            "authorAvatar": "{{commit.author.avatar}}",
            "timestamp": {{commit.created}}
          },
          "steps": [
            {{#each build.stages}}
              {{#each steps}}
              {
                "name": "{{name}}",
                "status": "{{status}}",
                "exitCode": {{exit_code}},
                "startTime": {{started}},
                "endTime": {{finished}}
              }{{#unless @last}},{{/unless}}
              {{/each}}
            {{#unless @last}},{{/unless}}
            {{/each}}
          ]
        }
    when:
      status:
        - success
        - failure
        - error
    depends_on:
      - install
      - build
      - deploy
