kind: pipeline
type: docker
name: valentine-pipeline

steps:
  - name: install
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm install

  - name: build
    image: node:20
    commands:
      - npm install -g pnpm
      - pnpm build
    environment:
      VITE_BASE_URL: /valentine/
    depends_on:
      - install

  - name: deploy
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      pages_directory: dist
    when:
      branch:
        - main
    depends_on:
      - build

  - name: notify
    image: plugins/webhook
    settings:
      urls:
        - https://webhook.site/ddb8c495-4a98-4bb0-a80e-56398ac4d92c
      method: POST
      content_type: application/json
      template: |
        {
          "repo": {
            "slug": "{{repo.slug}}",
            "name": "{{repo.name}}",
            "owner": "{{repo.owner}}",
            "link": "{{repo.link}}"
          },
          "build": {
            "number": {{build.number}},
            "status": "{{build.status}}",
            "event": "{{build.event}}",
            "link": "{{build.link}}",
            "started": {{build.started}},
            "finished": {{build.finished}}
          },
          "commit": {
            "sha": "{{commit.sha}}",
            "branch": "{{commit.branch}}",
            "message": "{{commit.message}}",
            "author": "{{commit.author}}"
          },
          "steps": {{tojson build.steps}},
          "pipeline": {
            "name": "{{pipeline.name}}",
            "status": "{{pipeline.status}}",
            "started": {{pipeline.started}},
            "finished": {{pipeline.finished}}
          }
        }
    when:
      status:
        - success
        - failure
        - error
    depends_on:
      - install
      - build
      - deploy
